config/routes.rb
Rails.application.routes.draw do

  post   'hello/use' 
  get    'hello/use' 
 
  resources 'hello'
  delete '/users/sign_out'
 
  devise_for :users
  root 'hello#index'
  get 'users/show'
  get 'questions/index'
  post'questions/index'
  get 'questions/new'=>'questions#new'
  post 'questions' =>'questions#create'
  get 'questions/show'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'questions/:id' => 'questions#show',as: 'question'
  get    'users/:id'   =>  'users#show'
  resources :questions do
    resources :likes, only: [:create, :destroy]
  end
  resources :questions do
    resource :situation
  end
  resources :comment1s,only: [:create]
  resources :questions do
    resources :comment1s
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user  
    belongs_to :question
end

app/models/comment1.rb
class Comment1 < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :question
  belongs_to :user
  validates_uniqueness_of :question_id, scope: :user_id
end

app/models/post_situation.rb
class PostSituation < ApplicationRecord
  belongs_to :question
  belongs_to :situation
end

app/models/question.rb
class Question < ApplicationRecord
    belongs_to :user 
    has_many :question_situations, dependent: :destroy
    has_many :situations, through: :question_situations
    has_many :comment1s
    
    mount_uploader :image, ImageUploader 
    has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

end

app/models/question_situation.rb
class QuestionSituation < ApplicationRecord
  belongs_to :question
  belongs_to :situation
end

app/models/situation.rb
class Situation < ApplicationRecord
    has_many :question_situations, dependent: :destroy
    has_many :questions, through: :question_situations
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
has_many :questions
has_many :comment1s
has_many :likes, dependent: :destroy
has_many :liked_questions, through: :likes, source: :question

def already_liked?(question)
  self.likes.exists?(question_id: question.id)
end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:age,:gender,:height,:weight]) # 新規登録時(sign_up時)にnameというキーのパラメーターを追加で許可する
    end
end

app/controllers/comment1s_controller.rb
class Comment1sController < ApplicationController
    before_action :authenticate_user!
    

    def create
      question = Question.find(params[:question_id])
      @comment = question.comment1s.build(comment_params)
      @comment.user_id = current_user.id
      if @comment.save
        flash[:success] = "コメントしました"
        redirect_back(fallback_location: root_path)
      else
        flash[:success] = "コメントできませんでした"
        redirect_back(fallback_location: root_path)
      end
    end
  
    private
  
      def comment_params
        params.require(:comment1).permit(:comment,{situation_ids: []})
      end
      
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def index
  end
  def use
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        @like = current_user.likes.create(question_id: params[:question_id])
        redirect_back(fallback_location: root_path)
        
      end
    
      def destroy
        @like = Like.find_by(question_id: params[:question_id], user_id: current_user.id)
        @like.destroy
        redirect_back(fallback_location: root_path)
        
       
      end

      def count
     
        @count=LIke.where(question_id: params[:question_id]).count
        
        
      end

    end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    
    @questions= params[:situation_id].present? ? Situation.find(params[:situation_id]).questions.page(params[:page]).per(4) : Question.all.page(params[:page]).per(4)
    

  end

  def new
 @question=Question.new

  end

  def show
    @question = Question.find(params[:id])
    @comments = @question.comment1s
      @comment = @question.comment1s.build
  
      @like = Like.new
  
      @menlikes=@question.liked_users.where(gender: "Men").count
      @womenlikes=@question.liked_users.where(gender:"Women").count
    
    end
  def create
    @question = Question.new(question_params)
    @question.user_id= current_user.id
    
    if @question.save
      redirect_to :action => "index"
    else
      redirect_to :action => "new"
    end

  end

  
  private
  def question_params
    params.require(:question).permit(:about,:user_id,:image, {situation_ids: []},:situation)
  end

 
  before_action :authenticate_user!
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @question= Question.where(user_id: current_user.id)
    
  end
  before_action :authenticate_user!
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment1s_helper.rb
module Comment1sHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comment1s/index.html.erb
a

app/views/hello/index.html.erb
<div class="hello">
<div class="image1">
<%= image_tag "coOde.png",  class: "image1", width: "300px", height: "150px" %>
</div>





<%= image_tag "blackT1.jpg",  class: "image", width: "300px", height: "900px" %>
<div class="pic-ctn">
    <%= image_tag "hello1.jpeg", alt:"" ,class: "pic", width: "800px", height: "1000px" %>
    <%= image_tag "hello2.jpeg", alt:"" ,class: "pic", width: "800px", height: "1000px" %>
    <%= image_tag "hello3.jpeg", alt:"" ,class: "pic" , width: "800px", height: "1000px"%>
  
    <%= image_tag "hello5.jpeg", alt:"" ,class: "pic" , width: "1000px", height: "1000px"%>
  </div>
  <div class="sentence">
  持ってる服をもっとおしゃれに
  <br>
  デートで、ベストな服をきるために
  
  <br>
  あなたに似合う服を見つけよう
  
  </div>
  


<%= button_to "ログイン",  questions_index_path ,class:"logbtn"%>

<%= button_to "つかいかた", "/hello/use",class:"usebtn" %>
</div>

app/views/hello/use.html.erb

<div class="commentbox" >
<div class="comment1">
<h2>あなたには、ファッションセンスはありますか？</h2>
<br>
自分に似合う服がわからない。
<br>
デートでどういう服を着ていけばいいかわからない。
</div>
<div class="pic1">
<%= image_tag "use1.jpeg", alt:"" ,class: "pic1" , width: "600px", height: "900px"%>
</div>
<div class="pic2">
<%= image_tag "use2.jpeg", alt:"" ,class: "pic1" , width: "600px", height: "900px"%>
</div>
<br>
<div class="comment2">
<h2>ファッションに関する悩みを解決します。</h2>
</div>
<div class="comment3">
<h1>How to use?</h1>
</div>

<div class="comment4">
1.あなたが着ている服を投稿するだけ
<br>
2.シチュエーションごとにあなたのコーディネートに対してほかのユーザーからアドバイスをもらえます
<br>
3.ファッションに関して困ってるユーザーにアドバイスをあげることも！
</div>

<div class="pic-ctn1">
    <%= image_tag "slide1.jpg", alt:"" ,class: "pic", width: "900px", height: "600px" %>
    <%= image_tag "slide2.jpg", alt:"" ,class: "pic", width: "900px", height: "600px" %>
    <%= image_tag "slide3.jpg", alt:"" ,class: "pic" , width: "900px", height: "600px"%>
  
   
  </div>
</div>

app/views/questions/index.html.erb
<br>
<div class="allbtn">

<%= button_to "#デート" , "/questions/index/", { method: :get, params: {situation_id: 1},class:"indexbtn1" }  %>
<br>
<%= button_to "#おでかけ" , "/questions/index/", { method: :get, params: {situation_id: 2} ,class:"indexbtn2"}  %>
<br>
<%= button_to "#お買い物" ,"/questions/index/", { method: :get, params: {situation_id: 3},class:"indexbtn3" }  %>
<br>
<%= button_to "#その他" , "/questions/index/", { method: :get, params: {situation_id: 4},class:"indexbtn4" }  %>
<br>
</div>
<div class="questions-container">
  <% @questions.each do |q| %>
    <div class="questions">
    <%= q.user.name %> 
    <br>
    
    <a href="/questions/<%= q.id %>"><%=  image_tag q.image_url, class:"userindex", width: "600px", height: "800px"%> </a>
    <br>
   <%= q.about %>
    <br>
  ♡<%= q.liked_users.count %>

  <% q.situations.each do |s| %>
     <%="#"+ s.body %>

     <% end %>
<br>
<%= q.created_at.strftime("%Y-%m-%d") %>
  <br>  
  <br>
 </div>
<% end %>
 </div>
<br>
<div class="body">
   <%= image_tag "blackT1.jpg",  class: "image", width: "300px", height: "900px" %>
</div>
<div class="body1">
   <%= image_tag "grayT1.jpg",  class: "image", width: "300px", height: "900px" %>
</div>
<br>
<div class="pagenate">
    <%= paginate  @questions %>
</div>

app/views/questions/new.html.erb
<div class="new">

<%= form_for @question do |f| %>
  <div class="new field1">
    <h2><%= f.label :コーディネート写真 %></h2>
     <br>
     </div>
     <div class="new imagefile">
     <%= f.file_field :image %>
     
    
     </div>
     <div class="new situation">
     <h2>シチュエーション</h2> 
     </div>
     <%= f.collection_check_boxes(:situation_ids, Situation.all, :id, :body) do |t| %>
      <div class="new field2">
        <%= t.label do %>
         
          <%= t.check_box %>
          <label><%= t.text %></label>
          </div>
     
          <% end %>
          <% end %>
          <div class="new comment">
         <h2><%= f.label :コメント %></h2>
         </div>
          <br>
          <div class="new field3">
         <br>
          <%= f.text_field :about, :size => 140 %>
          <div>
          <br>
          <div class="new field4">
      <%= f.submit "投稿",:class=>"btn" %>
          </div>
          
          <%= image_tag "newpage.jpeg",  class: "newimage", width: "300px", height: "470px" %>
      
</div>  
  
  
  <% end %>
    

app/views/questions/show.html.erb
<br>
<br>
<div class="question-show">

 <div class="ko ko-1">
 <%= @question.user.name %>
 </div>
<br>
  <div class="ko ko-2">
     <h1><%= image_tag @question.image_url %></h1><br>
  </div>
  <div class="ko ko-3">
    <%= @question.created_at.strftime("%Y-%m-%d")  %>
     <br> 
  </div>
   <div class="ko ko-4">
   
     <% if current_user.already_liked?(@question) %>
      <%= button_to 'やっぱ、似合ってない', question_like_path(@question), method: :delete,class:"likebtn1" %>
      <% else %>
       <%= button_to '似合ってる', question_likes_path(@question),class:"likebtn2" %>
      <% end %>
      </div>   
      <div class="ko ko-5">
       <h1>♡ <%= @question.likes.count %></h1>
      </div>
      <div class="ko ko-6">
          <h1><%= image_tag "men.jpg", width:"50px" %> :  <%= @menlikes %> 
       <%= image_tag "women.jpg", width:"50px" %>: <%= @womenlikes %>
        <br>
      </div>
      <div class="ko ko-7">
      <% @question.situations.each do |tag| %>
       <h2> <%= "#"+tag.body %> </h2>
       <% end %>
       </div>
       <br>
      <div class="ko ko-8">
      <h1><%= @question.about %></h1>
      <br>
      <br>
      </div>
     
</div>

<div class="comment-wrapper">
   
 <div class="comment-ko2">
  <% if user_signed_in? %>
    <%= form_with(model: [@question, @comment], local: true) do |f| %>
      
      <%= f.text_area :comment,rows:"3",cols:"80", placeholder:"アドバイスを入力",class:"advisetext"%>
      <i class="fa fa-envelope fa-lg fa-fw" aria-hidden="true"></i>
      
   <div class="comment-ko3">
      <%= button_tag type: "submit", class:"sendbtn" do  %>
        <i class="far fa-comment1s"></i> Send 
        <% end %>
        </div> 
        </div> 
      <br>


      
      <div class="comment-ko1">
<h2><font face＝"ＭＳ Ｐ明朝,ＭＳ 明朝">アドバイス一覧</font></h2>
 </div>

 
  <% @comments.each do |c| %>
    <div class="balloon">
    <figure class="balloon-image-left">
    <%= image_tag "user.jpeg" %>
    <figcaption class="balloon-image-description">
    <%= c.user.name unless c.user.blank? %>
    </figcaption>
    </figure>
    <div class="balloon-text-right">
    <p>
    <%= c.comment %>　
    </p>
    </div>
    </div> 
    <% end %>
 
      <% end %>
     
 
</div>
<% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "新規登録", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "パスワードをお忘れの方はこちら", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
<div class="title">
<h1>マイページ</h1>
</div>
<br>
<div class="title2">
<h3>過去の投稿</h3>
</div>
<div class="mypage-container">
<% @question.each do |q| %>
  <div class="mypage">
  <br>

  <a href="/questions/<%= q.id %>"><%=  image_tag q.image_url,  width: "600px", height: "800px"%> </a>
    <br>
    <%= q.about %>

    <% q.situations.each do |s| %>
     
      <%="#"+ s.body %>
      <% end %>
      <br>
      ♡ <%= q.likes.count %><br>
    
  </div>    
  <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
    <% end %>
</div>